image: node:18-alpine

pipelines:
  branches:
    main:
      - step:
          name: Deploy Main Branch to Prod Server
          deployment: production
          runs-on: 
            - linux
            - self.hosted
            - stsportz
            - prod
          script:
            - echo "Deploying build to EC2..."
            - apk update 
            - apk add openssh scp 
            - scp -o StrictHostKeyChecking=no -r ./ $EC2_USER@$EC2_HOST:$PROJECT_PATH
            - ssh -o StrictHostKeyChecking=no $EC2_USER@$EC2_HOST << 'EOF'
                sudo systemctl restart nginx
              EOF
